version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestOnPremRenderingProject
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: AllControlsPackageTest
  gitServerName: test
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: PoojaAnandGit
  gitBranch: main
